### PR TITLE
Add metrics for commit / rollback

### PR DESCRIPTION
**Pull request by petoju**
These metrics are useful when comparing multiple workloads and thus
should be exposed.

### CODE REVIEW

**Review by arvdias — APPROVED** [review]
LGTM

**Review by gsanchezgavier — APPROVED** [review]
Thanks @petoju  for the contribution!! Also adding the changelog and integration test case.
We will try to have the release soon

**Comment by arvdias** [comment]
Hi @petoju Sorry , can you resolve the conflicts please? We did a couple of changes in the main file and they're now conflicting with your PR.

**Comment by petoju** [comment]
@arvdias  conflicts should be resolved now.

**Comment by arvdias** [comment]
Merging this although we have a few build errors, but they are related to required credentials to perform some of the GH actions

**Pull request merged**
